# Deployment Manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: add-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: add
  template:
    metadata:
      labels:
        app: add
    spec:
      containers:
      - name: addcn
        image: 1anand1/add-task
        ports:
        - containerPort: 8000
        env:
        - name: CONNECTION_STRING
          # value: "Driver={ODBC Driver 17 for SQL Server};Server=tcp:hulk777.database.windows.net,1433;Database=database;Uid=hulk77;Pwd=Hulk00000000000;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
          valueFrom:
            secretKeyRef:
              key: CONNECTION_STRING
              name: todosecret

---
# Ingress manifests
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: add-ingress
  labels:
    app: get
spec:
  ingressClassName: azure-application-gateway
  rules:
  - host: add.bhushan.tech
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: add-svc
            port:
              number: 8000


---
# Service manifest
apiVersion: v1
kind: Service
metadata:
  name: add-svc
spec:
  selector:
    app: add
  ports:
    - port: 80
      targetPort: 8000
